# Generated by Django 5.2.7 on 2025-10-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('enrollment', models.BigIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
