# Generated by Django 5.2.7 on 2026-01-16 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0003_tags_course_tags_cachedquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedquery',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_tokens', to='searchapp.course'),
        ),
    ]
